module.exports = {
  "Start": "In Room LX",
  "Wake up": "Wake up",
  "Brush teeth": "Brush teeth",
  "Eat breakfast": "Eat a Meal",
  "Meditate": "Meditation",
  "Exercise": "EX 1",
  "Exercise 2": "EX 2 ",
  "Take bird bath": "EX 3",
  "Pray": "Pray",
  "Pray aloud": "Pray",
  "Play trashketball": "Pebbles 1",
  "Retrieve paper": "Pebbles Retri",
  "Stack stones": "Stones 1",
  "Stack stones 2": "Stones 2",
  "Knock down stones": "Stones 3",
  "Make fire": "Fire",
  "Put out fire": "Fire Out",
  "Dance": "Dance",
  "Do Yoga": "Yoga",
  "Look at family photos": "Photos",
  "Read": "Read",
  "Write line of song": "Song 1",
  "Write line of song 2": "Song 2",
  "Write line of song 3": "Song 3",
  "Write line of song 4": "Song 4",
  "Sing verse of song": "Song 5",
  "Tell": "Tell",
  "Donate organs": "Organs",
  "Request final meal": "Choose Meal",
  "Eat final meal": "no Isadora cue",
  "Hatch escape plan": "Escape",
  "Psych yourself up": "Psyche",
  "Make phone call": "Phone",
  "Write letter": "Letter",
  "Cast letter into sea": "Letter Sea",
  "Eat lunch": "no Isadora cue",
  "Eat dinner": "no Isadora cue",
  "Get ready for bed": "Go to Bed",
  "Sleep": "Sleep LX",
  "Dream": "Dream LX"
}